name: hello-world
on: push
jobs: 
  hello-world-job:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "$(cat hello_world.txt)"
      - name: use node.js
        uses: actions/setup-node@v4  # GitHub Marketplace 에 있는 action을 사용할 때는 Creator verifed by GitHub 인증이 된 action을 사용 / 혹은 lock the action on the Git SHA https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions
        with: 
          node-version: '18'
      - run: npm install
      - run: npm run build
